# Copied from Quasar Discord
# gitlab CI for deploying a quasar app to gitlab

# Modified from https://knasmueller.net/vue-js-on-gitlab-pages
#tags:
#  - quasar

stages:
  - code_build
  - image_build
  - deploy_nonprod
  - deploy_prod

build_dev_app:
 stage: code_build
 only: 
  - develop
 image: node:16
 tags:
  - benmapdevgitlab
 script:
  - cd bencloud-quasar
  - npm install -g @quasar/cli
  - npm install --progress=false
  - QENV=test quasar build
 artifacts:
  expire_in: 1 day
  paths:
   - bencloud-quasar/dist/spa

build_stage_app:
 stage: code_build
 only: 
  - main
 image: node:16
 tags:
  - benmapstagegitlab
 script:
  - cd bencloud-quasar
  - npm install -g @quasar/cli
  - npm install --progress=false
  - QENV=staging quasar build
 artifacts:
  expire_in: 1 day
  paths:
   - bencloud-quasar/dist/spa

build_dev_image:
 stage: image_build
 only:
  - develop
 tags:
  - benmapdevgitlab
 image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]
 script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/bencloudapp/Dockerfile-dev --destination $CI_REGISTRY_IMAGE/bencloudapp:$CI_COMMIT_SHORT_SHA
 dependencies:
  - build_dev_app

build_stage_image:
 stage: image_build
 only:
  - main
 tags:
  - benmapstagegitlab
 image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]
 script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/bencloudapp/Dockerfile-stage --destination $CI_REGISTRY_IMAGE/bencloudapp:$CI_COMMIT_SHORT_SHA
 dependencies:
  - build_stage_app

deploy_testdev:
 stage: deploy_nonprod
 only:
  - develop
 tags:
  - benmapdevgitlab
 when: manual
 image: dtzar/helm-kubectl
 script:
  - apk add gettext
  - kubectl config set-cluster benmap-shared-dev00 --server="$KUBE_URL"
  - kubectl config set-cluster benmap-shared-dev00 --certificate-authority=$KUBE_CA_PEM_FILE --embed-certs=true
  - kubectl config set-credentials gitlab --token="$KUBE_TOKEN"
  - kubectl config set-context default --cluster=benmap-shared-dev00 --user=gitlab --namespace="benmap-dev"
  - kubectl config use-context default
  - envsubst < k8s/bencloud-dev-app.yml | kubectl apply -f -
 environment:
  name: testdev
  url: https://dev.bencloud-dev.aws.epa.gov
  kubernetes:
   namespace: benmap-dev

deploy_staging:
 stage: deploy_nonprod
 only:
  - main
 tags:
  - benmapstagegitlab
 when: manual
 image: dtzar/helm-kubectl
 script:
  - apk add gettext
  - kubectl config set-cluster benmap-shared-stg00 --server="$KUBE_URL"
  - kubectl config set-cluster benmap-shared-stg00 --certificate-authority=$KUBE_CA_PEM_FILE --embed-certs=true
  - kubectl config set-credentials gitlab --token="$KUBE_TOKEN"
  - kubectl config set-context default --cluster=benmap-shared-stg00 --user=gitlab --namespace="benmap-stg"
  - kubectl config use-context default
  - envsubst < k8s/bencloud-stage-app.yml | kubectl apply -f -
 environment:
  name: staging
  url: https://stg.bencloud-stage.aws.epa.gov
  kubernetes:
   namespace: benmap-stg
#he quasar.conf.js also needs
# comment for now     publicPath: process.env.NODE_ENV === 'production' ? '/rep$

#change for forcing pipeline 002
