# Copied from Quasar Discord
# gitlab CI for deploying a quasar app to gitlab

# Modified from https://knasmueller.net/vue-js-on-gitlab-pages
#tags:
#  - quasar

stages:
  - code_build
  - image_build
  - image_scan
  - deploy_nonprod

# Set K8s context of GitLab Agent
.kube-dev-context:
  before_script:
  - kubectl config use-context "$KUBE_DEV_CONTEXT";

.kube-stg-context:
  before_script:
  - kubectl config use-context "$KUBE_STG_CONTEXT";

build_dev_app:
 stage: code_build
 only: 
  - develop
 image: node:16
 tags:
  - benmapdevgitlab
 script:
  - cd bencloud-quasar
  - npm install -g @quasar/cli
  - npm install --progress=false
  - QENV=test quasar build
 artifacts:
  expire_in: 1 day
  paths:
   - bencloud-quasar/dist/spa

build_stage_app:
 stage: code_build
 only: 
  - tags
 image: node:16
 tags:
  - benmapstagegitlab
 script:
  - cd bencloud-quasar
  - npm install -g @quasar/cli
  - npm install --progress=false
  - QENV=production quasar build
 artifacts:
  expire_in: 1 day
  paths:
   - bencloud-quasar/dist/spa

build_dev_image:
 stage: image_build
 only:
  - develop
 tags:
  - benmapdevgitlab
 image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]
 script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/bencloudapp/Dockerfile-dev --destination $CI_REGISTRY_IMAGE/bencloudapp:$CI_COMMIT_SHORT_SHA
 dependencies:
  - build_dev_app

build_stage_image:
 stage: image_build
 only:
  - tags
 tags:
  - benmapstagegitlab
 image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]
 script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/bencloudapp/Dockerfile-stage --destination $CI_REGISTRY_IMAGE/bencloudapp:$CI_COMMIT_SHORT_SHA
 dependencies:
  - build_stage_app

prisma_cloud_compute_scan:
  stage: image_scan
  only: 
  - develop
  - tags
  tags:
    - twistcli
  variables:
    GIT_STRATEGY: none
  script:
    - 'export PRISMA_CI_TOKEN=$(curl -kH "Content-Type: application/json" -d "{\"username\":\"$PRISMA_CI_USERNAME\", \"password\":\"$PRISMA_CI_PASSWORD\"}" https://prismacloud.epa.gov/api/v32.01/authenticate | jq -r .token)'
    - 'curl --progress-bar -L -k --header "Authorization: Bearer $PRISMA_CI_TOKEN" https://prismacloud.epa.gov/api/v1/util/twistcli > twistcli; chmod a+x twistcli;'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/bencloudapp:$CI_COMMIT_SHORT_SHA
    - ./twistcli images scan $CI_REGISTRY_IMAGE/bencloudapp:$CI_COMMIT_SHORT_SHA --address=https://prismacloud.epa.gov --details --token=$PRISMA_CI_TOKEN
  after_script:
    # Cleanup the above space use on Runner.
    - rm -rf $CI_PROJECT_DIR

deploy_testdev:
 stage: deploy_nonprod
 only:
  - develop
 tags:
  - benmapdevgitlab
 when: manual
 image: dtzar/helm-kubectl
 script:
  - apk add gettext
  - kubectl config use-context "$KUBE_CONTEXT"
  - envsubst < k8s/bencloud-dev-app.yml | kubectl apply --validate=false -f -
  # - kubectl apply -f k8s/bencloud-dev-app.yml -n benmap-dev
 environment:
  name: testdev
  url: https://dev.bencloud-dev.aws.epa.gov
  kubernetes:
   namespace: benmap-dev

deploy_staging:
 stage: deploy_nonprod
 only:
  - tags
 tags:
  - benmapstagegitlab
 when: manual
 image: dtzar/helm-kubectl
 script:
  - apk add gettext
  - kubectl config use-context "$KUBE_CONTEXT"
  - envsubst < k8s/bencloud-stage-app.yml | kubectl apply --validate=false -f -
  # - kubectl apply -f k8s/bencloud-stage-app.yml -n benmap-stg
 environment:
  name: staging
  url: https://stg.bencloud-stage.aws.epa.gov
  kubernetes:
   namespace: benmap-stg
#he quasar.conf.js also needs
# comment for now     publicPath: process.env.NODE_ENV === 'production' ? '/rep$

#change for forcing pipeline 002
