/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.AgeRange;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgeRangeRecord extends UpdatableRecordImpl<AgeRangeRecord> implements Record5<Integer, Integer, String, Short, Short> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.age_range.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.age_range.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.age_range.pop_config_id</code>.
     */
    public void setPopConfigId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.age_range.pop_config_id</code>.
     */
    public Integer getPopConfigId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.age_range.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.age_range.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>data.age_range.start_age</code>.
     */
    public void setStartAge(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.age_range.start_age</code>.
     */
    public Short getStartAge() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>data.age_range.end_age</code>.
     */
    public void setEndAge(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.age_range.end_age</code>.
     */
    public Short getEndAge() {
        return (Short) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Short, Short> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Short, Short> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AgeRange.AGE_RANGE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AgeRange.AGE_RANGE.POP_CONFIG_ID;
    }

    @Override
    public Field<String> field3() {
        return AgeRange.AGE_RANGE.NAME;
    }

    @Override
    public Field<Short> field4() {
        return AgeRange.AGE_RANGE.START_AGE;
    }

    @Override
    public Field<Short> field5() {
        return AgeRange.AGE_RANGE.END_AGE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPopConfigId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Short component4() {
        return getStartAge();
    }

    @Override
    public Short component5() {
        return getEndAge();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPopConfigId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Short value4() {
        return getStartAge();
    }

    @Override
    public Short value5() {
        return getEndAge();
    }

    @Override
    public AgeRangeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AgeRangeRecord value2(Integer value) {
        setPopConfigId(value);
        return this;
    }

    @Override
    public AgeRangeRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public AgeRangeRecord value4(Short value) {
        setStartAge(value);
        return this;
    }

    @Override
    public AgeRangeRecord value5(Short value) {
        setEndAge(value);
        return this;
    }

    @Override
    public AgeRangeRecord values(Integer value1, Integer value2, String value3, Short value4, Short value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgeRangeRecord
     */
    public AgeRangeRecord() {
        super(AgeRange.AGE_RANGE);
    }

    /**
     * Create a detached, initialised AgeRangeRecord
     */
    public AgeRangeRecord(Integer id, Integer popConfigId, String name, Short startAge, Short endAge) {
        super(AgeRange.AGE_RANGE);

        setId(id);
        setPopConfigId(popConfigId);
        setName(name);
        setStartAge(startAge);
        setEndAge(endAge);
    }
}
