/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.PollutantMetric;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollutantMetricRecord extends UpdatableRecordImpl<PollutantMetricRecord> implements Record9<Integer, Integer, String, Short, Short, Short, Short, Short, Short> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.pollutant_metric.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.pollutant_metric.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.pollutant_metric.pollutant_id</code>.
     */
    public void setPollutantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.pollutant_metric.pollutant_id</code>.
     */
    public Integer getPollutantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.pollutant_metric.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.pollutant_metric.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>data.pollutant_metric.hourly_metric_generation</code>.
     */
    public void setHourlyMetricGeneration(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.pollutant_metric.hourly_metric_generation</code>.
     */
    public Short getHourlyMetricGeneration() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>data.pollutant_metric.window_size</code>.
     */
    public void setWindowSize(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.pollutant_metric.window_size</code>.
     */
    public Short getWindowSize() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>data.pollutant_metric.window_statistic</code>.
     */
    public void setWindowStatistic(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>data.pollutant_metric.window_statistic</code>.
     */
    public Short getWindowStatistic() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>data.pollutant_metric.start_hour</code>.
     */
    public void setStartHour(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>data.pollutant_metric.start_hour</code>.
     */
    public Short getStartHour() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>data.pollutant_metric.end_hour</code>.
     */
    public void setEndHour(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>data.pollutant_metric.end_hour</code>.
     */
    public Short getEndHour() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>data.pollutant_metric.daily_statistic</code>.
     */
    public void setDailyStatistic(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>data.pollutant_metric.daily_statistic</code>.
     */
    public Short getDailyStatistic() {
        return (Short) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, String, Short, Short, Short, Short, Short, Short> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, String, Short, Short, Short, Short, Short, Short> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PollutantMetric.POLLUTANT_METRIC.ID;
    }

    @Override
    public Field<Integer> field2() {
        return PollutantMetric.POLLUTANT_METRIC.POLLUTANT_ID;
    }

    @Override
    public Field<String> field3() {
        return PollutantMetric.POLLUTANT_METRIC.NAME;
    }

    @Override
    public Field<Short> field4() {
        return PollutantMetric.POLLUTANT_METRIC.HOURLY_METRIC_GENERATION;
    }

    @Override
    public Field<Short> field5() {
        return PollutantMetric.POLLUTANT_METRIC.WINDOW_SIZE;
    }

    @Override
    public Field<Short> field6() {
        return PollutantMetric.POLLUTANT_METRIC.WINDOW_STATISTIC;
    }

    @Override
    public Field<Short> field7() {
        return PollutantMetric.POLLUTANT_METRIC.START_HOUR;
    }

    @Override
    public Field<Short> field8() {
        return PollutantMetric.POLLUTANT_METRIC.END_HOUR;
    }

    @Override
    public Field<Short> field9() {
        return PollutantMetric.POLLUTANT_METRIC.DAILY_STATISTIC;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPollutantId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Short component4() {
        return getHourlyMetricGeneration();
    }

    @Override
    public Short component5() {
        return getWindowSize();
    }

    @Override
    public Short component6() {
        return getWindowStatistic();
    }

    @Override
    public Short component7() {
        return getStartHour();
    }

    @Override
    public Short component8() {
        return getEndHour();
    }

    @Override
    public Short component9() {
        return getDailyStatistic();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPollutantId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Short value4() {
        return getHourlyMetricGeneration();
    }

    @Override
    public Short value5() {
        return getWindowSize();
    }

    @Override
    public Short value6() {
        return getWindowStatistic();
    }

    @Override
    public Short value7() {
        return getStartHour();
    }

    @Override
    public Short value8() {
        return getEndHour();
    }

    @Override
    public Short value9() {
        return getDailyStatistic();
    }

    @Override
    public PollutantMetricRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PollutantMetricRecord value2(Integer value) {
        setPollutantId(value);
        return this;
    }

    @Override
    public PollutantMetricRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public PollutantMetricRecord value4(Short value) {
        setHourlyMetricGeneration(value);
        return this;
    }

    @Override
    public PollutantMetricRecord value5(Short value) {
        setWindowSize(value);
        return this;
    }

    @Override
    public PollutantMetricRecord value6(Short value) {
        setWindowStatistic(value);
        return this;
    }

    @Override
    public PollutantMetricRecord value7(Short value) {
        setStartHour(value);
        return this;
    }

    @Override
    public PollutantMetricRecord value8(Short value) {
        setEndHour(value);
        return this;
    }

    @Override
    public PollutantMetricRecord value9(Short value) {
        setDailyStatistic(value);
        return this;
    }

    @Override
    public PollutantMetricRecord values(Integer value1, Integer value2, String value3, Short value4, Short value5, Short value6, Short value7, Short value8, Short value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PollutantMetricRecord
     */
    public PollutantMetricRecord() {
        super(PollutantMetric.POLLUTANT_METRIC);
    }

    /**
     * Create a detached, initialised PollutantMetricRecord
     */
    public PollutantMetricRecord(Integer id, Integer pollutantId, String name, Short hourlyMetricGeneration, Short windowSize, Short windowStatistic, Short startHour, Short endHour, Short dailyStatistic) {
        super(PollutantMetric.POLLUTANT_METRIC);

        setId(id);
        setPollutantId(pollutantId);
        setName(name);
        setHourlyMetricGeneration(hourlyMetricGeneration);
        setWindowSize(windowSize);
        setWindowStatistic(windowStatistic);
        setStartHour(startHour);
        setEndHour(endHour);
        setDailyStatistic(dailyStatistic);
    }
}
