/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.PopulationEntry;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PopulationEntryRecord extends TableRecordImpl<PopulationEntryRecord> implements Record10<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Long, Short, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.population_entry.pop_dataset_id</code>.
     */
    public void setPopDatasetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.population_entry.pop_dataset_id</code>.
     */
    public Integer getPopDatasetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.population_entry.race_id</code>.
     */
    public void setRaceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.population_entry.race_id</code>.
     */
    public Integer getRaceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.population_entry.ethnicity_id</code>.
     */
    public void setEthnicityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.population_entry.ethnicity_id</code>.
     */
    public Integer getEthnicityId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>data.population_entry.gender_id</code>.
     */
    public void setGenderId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.population_entry.gender_id</code>.
     */
    public Integer getGenderId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>data.population_entry.age_range_id</code>.
     */
    public void setAgeRangeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.population_entry.age_range_id</code>.
     */
    public Integer getAgeRangeId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>data.population_entry.grid_col</code>.
     */
    public void setGridCol(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>data.population_entry.grid_col</code>.
     */
    public Integer getGridCol() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>data.population_entry.grid_row</code>.
     */
    public void setGridRow(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>data.population_entry.grid_row</code>.
     */
    public Integer getGridRow() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>data.population_entry.grid_cell_id</code>.
     */
    public void setGridCellId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>data.population_entry.grid_cell_id</code>.
     */
    public Long getGridCellId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>data.population_entry.pop_year</code>.
     */
    public void setPopYear(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>data.population_entry.pop_year</code>.
     */
    public Short getPopYear() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>data.population_entry.pop_value</code>.
     */
    public void setPopValue(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>data.population_entry.pop_value</code>.
     */
    public BigDecimal getPopValue() {
        return (BigDecimal) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Long, Short, BigDecimal> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Long, Short, BigDecimal> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PopulationEntry.POPULATION_ENTRY.POP_DATASET_ID;
    }

    @Override
    public Field<Integer> field2() {
        return PopulationEntry.POPULATION_ENTRY.RACE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return PopulationEntry.POPULATION_ENTRY.ETHNICITY_ID;
    }

    @Override
    public Field<Integer> field4() {
        return PopulationEntry.POPULATION_ENTRY.GENDER_ID;
    }

    @Override
    public Field<Integer> field5() {
        return PopulationEntry.POPULATION_ENTRY.AGE_RANGE_ID;
    }

    @Override
    public Field<Integer> field6() {
        return PopulationEntry.POPULATION_ENTRY.GRID_COL;
    }

    @Override
    public Field<Integer> field7() {
        return PopulationEntry.POPULATION_ENTRY.GRID_ROW;
    }

    @Override
    public Field<Long> field8() {
        return PopulationEntry.POPULATION_ENTRY.GRID_CELL_ID;
    }

    @Override
    public Field<Short> field9() {
        return PopulationEntry.POPULATION_ENTRY.POP_YEAR;
    }

    @Override
    public Field<BigDecimal> field10() {
        return PopulationEntry.POPULATION_ENTRY.POP_VALUE;
    }

    @Override
    public Integer component1() {
        return getPopDatasetId();
    }

    @Override
    public Integer component2() {
        return getRaceId();
    }

    @Override
    public Integer component3() {
        return getEthnicityId();
    }

    @Override
    public Integer component4() {
        return getGenderId();
    }

    @Override
    public Integer component5() {
        return getAgeRangeId();
    }

    @Override
    public Integer component6() {
        return getGridCol();
    }

    @Override
    public Integer component7() {
        return getGridRow();
    }

    @Override
    public Long component8() {
        return getGridCellId();
    }

    @Override
    public Short component9() {
        return getPopYear();
    }

    @Override
    public BigDecimal component10() {
        return getPopValue();
    }

    @Override
    public Integer value1() {
        return getPopDatasetId();
    }

    @Override
    public Integer value2() {
        return getRaceId();
    }

    @Override
    public Integer value3() {
        return getEthnicityId();
    }

    @Override
    public Integer value4() {
        return getGenderId();
    }

    @Override
    public Integer value5() {
        return getAgeRangeId();
    }

    @Override
    public Integer value6() {
        return getGridCol();
    }

    @Override
    public Integer value7() {
        return getGridRow();
    }

    @Override
    public Long value8() {
        return getGridCellId();
    }

    @Override
    public Short value9() {
        return getPopYear();
    }

    @Override
    public BigDecimal value10() {
        return getPopValue();
    }

    @Override
    public PopulationEntryRecord value1(Integer value) {
        setPopDatasetId(value);
        return this;
    }

    @Override
    public PopulationEntryRecord value2(Integer value) {
        setRaceId(value);
        return this;
    }

    @Override
    public PopulationEntryRecord value3(Integer value) {
        setEthnicityId(value);
        return this;
    }

    @Override
    public PopulationEntryRecord value4(Integer value) {
        setGenderId(value);
        return this;
    }

    @Override
    public PopulationEntryRecord value5(Integer value) {
        setAgeRangeId(value);
        return this;
    }

    @Override
    public PopulationEntryRecord value6(Integer value) {
        setGridCol(value);
        return this;
    }

    @Override
    public PopulationEntryRecord value7(Integer value) {
        setGridRow(value);
        return this;
    }

    @Override
    public PopulationEntryRecord value8(Long value) {
        setGridCellId(value);
        return this;
    }

    @Override
    public PopulationEntryRecord value9(Short value) {
        setPopYear(value);
        return this;
    }

    @Override
    public PopulationEntryRecord value10(BigDecimal value) {
        setPopValue(value);
        return this;
    }

    @Override
    public PopulationEntryRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Long value8, Short value9, BigDecimal value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PopulationEntryRecord
     */
    public PopulationEntryRecord() {
        super(PopulationEntry.POPULATION_ENTRY);
    }

    /**
     * Create a detached, initialised PopulationEntryRecord
     */
    public PopulationEntryRecord(Integer popDatasetId, Integer raceId, Integer ethnicityId, Integer genderId, Integer ageRangeId, Integer gridCol, Integer gridRow, Long gridCellId, Short popYear, BigDecimal popValue) {
        super(PopulationEntry.POPULATION_ENTRY);

        setPopDatasetId(popDatasetId);
        setRaceId(raceId);
        setEthnicityId(ethnicityId);
        setGenderId(genderId);
        setAgeRangeId(ageRangeId);
        setGridCol(gridCol);
        setGridRow(gridRow);
        setGridCellId(gridCellId);
        setPopYear(popYear);
        setPopValue(popValue);
    }
}
