/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables.records;


import gov.epa.bencloud.server.database.jooq.data.tables.VariableEntry;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VariableEntryRecord extends UpdatableRecordImpl<VariableEntryRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.variable_entry.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.variable_entry.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.variable_entry.variable_dataset_id</code>.
     */
    public void setVariableDatasetId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.variable_entry.variable_dataset_id</code>.
     */
    public Integer getVariableDatasetId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.variable_entry.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.variable_entry.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VariableEntry.VARIABLE_ENTRY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return VariableEntry.VARIABLE_ENTRY.VARIABLE_DATASET_ID;
    }

    @Override
    public Field<String> field3() {
        return VariableEntry.VARIABLE_ENTRY.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getVariableDatasetId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getVariableDatasetId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public VariableEntryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VariableEntryRecord value2(Integer value) {
        setVariableDatasetId(value);
        return this;
    }

    @Override
    public VariableEntryRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public VariableEntryRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VariableEntryRecord
     */
    public VariableEntryRecord() {
        super(VariableEntry.VARIABLE_ENTRY);
    }

    /**
     * Create a detached, initialised VariableEntryRecord
     */
    public VariableEntryRecord(Integer id, Integer variableDatasetId, String name) {
        super(VariableEntry.VARIABLE_ENTRY);

        setId(id);
        setVariableDatasetId(variableDatasetId);
        setName(name);
    }
}
