FROM nginx:stable-alpine

#WORKDIR /var/www

#RUN mkdir -p /var/www
#COPY /bencloud-quasar/dist/spa/ /var/www/
COPY /bencloud-quasar/dist/spa/ /usr/share/nginx/html/
# COPY ./docker/bencloudapp/nginx.conf /etc/nginx/

# RUN apt-get -y update \
#    && apt-get -y upgrade \
#    && adduser -D -H -u 1000 -s /bin/bash www-data -G www-data

# COPY ./docker/bencloudapp/sites/default-dev.conf /etc/nginx/sites-available/default.conf

RUN chmod 555 /docker-entrypoint.sh

# TESTING
RUN if [ -f /docker-entrypoint.sh ]; then \
    echo "File /docker-entrypoint.sh exists."; \
    cat /docker-entrypoint.sh; \
    else \
    echo "File /docker-entrypoint.sh DOES NOT EXIST."; \
    fi
# END TESTING


ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 80
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]

