/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq;


import gov.epa.bencloud.server.database.jooq.tables.IncomeGrowthAdjDataset;
import gov.epa.bencloud.server.database.jooq.tables.IncomeGrowthAdjFactor;
import gov.epa.bencloud.server.database.jooq.tables.Pollutant;
import gov.epa.bencloud.server.database.jooq.tables.PollutantMetric;
import gov.epa.bencloud.server.database.jooq.tables.PopConfig;
import gov.epa.bencloud.server.database.jooq.tables.PopulationDataset;
import gov.epa.bencloud.server.database.jooq.tables.Race;
import gov.epa.bencloud.server.database.jooq.tables.SeasonalMetric;
import gov.epa.bencloud.server.database.jooq.tables.SeasonalMetricSeason;
import gov.epa.bencloud.server.database.jooq.tables.records.IncomeGrowthAdjDatasetRecord;
import gov.epa.bencloud.server.database.jooq.tables.records.IncomeGrowthAdjFactorRecord;
import gov.epa.bencloud.server.database.jooq.tables.records.PollutantMetricRecord;
import gov.epa.bencloud.server.database.jooq.tables.records.PollutantRecord;
import gov.epa.bencloud.server.database.jooq.tables.records.PopConfigRecord;
import gov.epa.bencloud.server.database.jooq.tables.records.PopulationDatasetRecord;
import gov.epa.bencloud.server.database.jooq.tables.records.RaceRecord;
import gov.epa.bencloud.server.database.jooq.tables.records.SeasonalMetricRecord;
import gov.epa.bencloud.server.database.jooq.tables.records.SeasonalMetricSeasonRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * data.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<IncomeGrowthAdjDatasetRecord> INCOME_GROWTH_ADJ_DATASET_PKEY = Internal.createUniqueKey(IncomeGrowthAdjDataset.INCOME_GROWTH_ADJ_DATASET, DSL.name("income_growth_adj_dataset_pkey"), new TableField[] { IncomeGrowthAdjDataset.INCOME_GROWTH_ADJ_DATASET.ID }, true);
    public static final UniqueKey<IncomeGrowthAdjFactorRecord> INCOME_GROWTH_ADJ_FACTOR_PKEY = Internal.createUniqueKey(IncomeGrowthAdjFactor.INCOME_GROWTH_ADJ_FACTOR, DSL.name("income_growth_adj_factor_pkey"), new TableField[] { IncomeGrowthAdjFactor.INCOME_GROWTH_ADJ_FACTOR.ID }, true);
    public static final UniqueKey<PollutantRecord> POLLUTANT_PKEY = Internal.createUniqueKey(Pollutant.POLLUTANT, DSL.name("pollutant_pkey"), new TableField[] { Pollutant.POLLUTANT.ID }, true);
    public static final UniqueKey<PollutantMetricRecord> POLLUTANT_METRIC_PKEY = Internal.createUniqueKey(PollutantMetric.POLLUTANT_METRIC, DSL.name("pollutant_metric_pkey"), new TableField[] { PollutantMetric.POLLUTANT_METRIC.ID }, true);
    public static final UniqueKey<PopConfigRecord> POP_CONFIG_PKEY = Internal.createUniqueKey(PopConfig.POP_CONFIG, DSL.name("pop_config_pkey"), new TableField[] { PopConfig.POP_CONFIG.ID }, true);
    public static final UniqueKey<PopulationDatasetRecord> POPULATION_DATASET_PKEY = Internal.createUniqueKey(PopulationDataset.POPULATION_DATASET, DSL.name("population_dataset_pkey"), new TableField[] { PopulationDataset.POPULATION_DATASET.ID }, true);
    public static final UniqueKey<RaceRecord> RACE_PKEY = Internal.createUniqueKey(Race.RACE, DSL.name("race_pkey"), new TableField[] { Race.RACE.ID }, true);
    public static final UniqueKey<SeasonalMetricRecord> SEASONAL_METRIC_PKEY = Internal.createUniqueKey(SeasonalMetric.SEASONAL_METRIC, DSL.name("seasonal_metric_pkey"), new TableField[] { SeasonalMetric.SEASONAL_METRIC.ID }, true);
    public static final UniqueKey<SeasonalMetricSeasonRecord> SEASONAL_METRIC_SEASON_PKEY = Internal.createUniqueKey(SeasonalMetricSeason.SEASONAL_METRIC_SEASON, DSL.name("seasonal_metric_season_pkey"), new TableField[] { SeasonalMetricSeason.SEASONAL_METRIC_SEASON.ID }, true);
}
