export default function () {
  return {
    pollutantFriendlyName: "",
    pollutantName: "",
    pollutantId: null,
    populationDatasetId: null,
    populationDatasetName: "",
    populationYearsSelected: [],
    populationYears: [],
    populationGroups: [],
    populationGroupIds: [],
    populationGroupNames: [],
    prePolicyAirQualityId: null,
    prePolicyAirQualityName: "",
    prePolicyGridDefinitionId: [],
    prePolicyGridDefinitionName: "",
    prePolicyAirQualityMetricId: null,
    prePolicyAirQualityGroupName: null,
    postPolicyAirQualityId: [],
    postPolicyAirQualityName: [],
    postPolicyGridDefinitionId: [],
    postPolicyGridDefinitionName: [],
    postPolicyAirQualitySelection: null,
    postPolicyAirQualityMetricId: [],
    postPolicyAirQualityGroupName: null,
    exposureFunctionGroup: null,
    exposureFunctionGroupId: null,
    exposureFunctionGroupName: null,
    location,
    airQualityLayers: null,
    stepNumber: 1,
    applyYearsToAll: false,
    batchTaskObject: null,
  }
}
