/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables.records;


import gov.epa.bencloud.server.database.jooq.tables.AirQualityLayer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AirQualityLayerRecord extends UpdatableRecordImpl<AirQualityLayerRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.air_quality_layer.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.air_quality_layer.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>data.air_quality_layer.pollutant_id</code>.
     */
    public void setPollutantId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.pollutant_id</code>.
     */
    public Integer getPollutantId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>data.air_quality_layer.grid_definition_id</code>.
     */
    public void setGridDefinitionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.air_quality_layer.grid_definition_id</code>.
     */
    public Integer getGridDefinitionId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AirQualityLayer.AIR_QUALITY_LAYER.ID;
    }

    @Override
    public Field<String> field2() {
        return AirQualityLayer.AIR_QUALITY_LAYER.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return AirQualityLayer.AIR_QUALITY_LAYER.POLLUTANT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return AirQualityLayer.AIR_QUALITY_LAYER.GRID_DEFINITION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getPollutantId();
    }

    @Override
    public Integer component4() {
        return getGridDefinitionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getPollutantId();
    }

    @Override
    public Integer value4() {
        return getGridDefinitionId();
    }

    @Override
    public AirQualityLayerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value3(Integer value) {
        setPollutantId(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord value4(Integer value) {
        setGridDefinitionId(value);
        return this;
    }

    @Override
    public AirQualityLayerRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AirQualityLayerRecord
     */
    public AirQualityLayerRecord() {
        super(AirQualityLayer.AIR_QUALITY_LAYER);
    }

    /**
     * Create a detached, initialised AirQualityLayerRecord
     */
    public AirQualityLayerRecord(Integer id, String name, Integer pollutantId, Integer gridDefinitionId) {
        super(AirQualityLayer.AIR_QUALITY_LAYER);

        setId(id);
        setName(name);
        setPollutantId(pollutantId);
        setGridDefinitionId(gridDefinitionId);
    }
}
