/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables.records;


import gov.epa.bencloud.server.database.jooq.tables.HifResultDataset;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HifResultDatasetRecord extends UpdatableRecordImpl<HifResultDatasetRecord> implements Record7<Integer, String, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.hif_result_dataset.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.hif_result_dataset.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.hif_result_dataset.task_uuid</code>.
     */
    public void setTaskUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.hif_result_dataset.task_uuid</code>.
     */
    public String getTaskUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>data.hif_result_dataset.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.hif_result_dataset.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>data.hif_result_dataset.population_dataset_id</code>.
     */
    public void setPopulationDatasetId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.hif_result_dataset.population_dataset_id</code>.
     */
    public Integer getPopulationDatasetId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>data.hif_result_dataset.population_year</code>.
     */
    public void setPopulationYear(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.hif_result_dataset.population_year</code>.
     */
    public Integer getPopulationYear() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>data.hif_result_dataset.baseline_aq_layer_id</code>.
     */
    public void setBaselineAqLayerId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>data.hif_result_dataset.baseline_aq_layer_id</code>.
     */
    public Integer getBaselineAqLayerId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>data.hif_result_dataset.scenario_aq_layer_id</code>.
     */
    public void setScenarioAqLayerId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>data.hif_result_dataset.scenario_aq_layer_id</code>.
     */
    public Integer getScenarioAqLayerId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return HifResultDataset.HIF_RESULT_DATASET.ID;
    }

    @Override
    public Field<String> field2() {
        return HifResultDataset.HIF_RESULT_DATASET.TASK_UUID;
    }

    @Override
    public Field<String> field3() {
        return HifResultDataset.HIF_RESULT_DATASET.NAME;
    }

    @Override
    public Field<Integer> field4() {
        return HifResultDataset.HIF_RESULT_DATASET.POPULATION_DATASET_ID;
    }

    @Override
    public Field<Integer> field5() {
        return HifResultDataset.HIF_RESULT_DATASET.POPULATION_YEAR;
    }

    @Override
    public Field<Integer> field6() {
        return HifResultDataset.HIF_RESULT_DATASET.BASELINE_AQ_LAYER_ID;
    }

    @Override
    public Field<Integer> field7() {
        return HifResultDataset.HIF_RESULT_DATASET.SCENARIO_AQ_LAYER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTaskUuid();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer component4() {
        return getPopulationDatasetId();
    }

    @Override
    public Integer component5() {
        return getPopulationYear();
    }

    @Override
    public Integer component6() {
        return getBaselineAqLayerId();
    }

    @Override
    public Integer component7() {
        return getScenarioAqLayerId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTaskUuid();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Integer value4() {
        return getPopulationDatasetId();
    }

    @Override
    public Integer value5() {
        return getPopulationYear();
    }

    @Override
    public Integer value6() {
        return getBaselineAqLayerId();
    }

    @Override
    public Integer value7() {
        return getScenarioAqLayerId();
    }

    @Override
    public HifResultDatasetRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public HifResultDatasetRecord value2(String value) {
        setTaskUuid(value);
        return this;
    }

    @Override
    public HifResultDatasetRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public HifResultDatasetRecord value4(Integer value) {
        setPopulationDatasetId(value);
        return this;
    }

    @Override
    public HifResultDatasetRecord value5(Integer value) {
        setPopulationYear(value);
        return this;
    }

    @Override
    public HifResultDatasetRecord value6(Integer value) {
        setBaselineAqLayerId(value);
        return this;
    }

    @Override
    public HifResultDatasetRecord value7(Integer value) {
        setScenarioAqLayerId(value);
        return this;
    }

    @Override
    public HifResultDatasetRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HifResultDatasetRecord
     */
    public HifResultDatasetRecord() {
        super(HifResultDataset.HIF_RESULT_DATASET);
    }

    /**
     * Create a detached, initialised HifResultDatasetRecord
     */
    public HifResultDatasetRecord(Integer id, String taskUuid, String name, Integer populationDatasetId, Integer populationYear, Integer baselineAqLayerId, Integer scenarioAqLayerId) {
        super(HifResultDataset.HIF_RESULT_DATASET);

        setId(id);
        setTaskUuid(taskUuid);
        setName(name);
        setPopulationDatasetId(populationDatasetId);
        setPopulationYear(populationYear);
        setBaselineAqLayerId(baselineAqLayerId);
        setScenarioAqLayerId(scenarioAqLayerId);
    }
}
