/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables.records;


import gov.epa.bencloud.server.database.jooq.tables.HifResults;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HifResultsRecord extends TableRecordImpl<HifResultsRecord> implements Record8<Integer, Integer, Integer, Integer, Long, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.hif_results.hif_result_dataset_id</code>.
     */
    public void setHifResultDatasetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.hif_results.hif_result_dataset_id</code>.
     */
    public Integer getHifResultDatasetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.hif_results.hif_id</code>.
     */
    public void setHifId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.hif_results.hif_id</code>.
     */
    public Integer getHifId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.hif_results.grid_col</code>.
     */
    public void setGridCol(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.hif_results.grid_col</code>.
     */
    public Integer getGridCol() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>data.hif_results.grid_row</code>.
     */
    public void setGridRow(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.hif_results.grid_row</code>.
     */
    public Integer getGridRow() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>data.hif_results.grid_cell_id</code>.
     */
    public void setGridCellId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.hif_results.grid_cell_id</code>.
     */
    public Long getGridCellId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>data.hif_results.population</code>.
     */
    public void setPopulation(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>data.hif_results.population</code>.
     */
    public BigDecimal getPopulation() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>data.hif_results.delta</code>.
     */
    public void setDelta(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>data.hif_results.delta</code>.
     */
    public BigDecimal getDelta() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>data.hif_results.result</code>.
     */
    public void setResult(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>data.hif_results.result</code>.
     */
    public BigDecimal getResult() {
        return (BigDecimal) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, Integer, Long, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, Integer, Long, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return HifResults.HIF_RESULTS.HIF_RESULT_DATASET_ID;
    }

    @Override
    public Field<Integer> field2() {
        return HifResults.HIF_RESULTS.HIF_ID;
    }

    @Override
    public Field<Integer> field3() {
        return HifResults.HIF_RESULTS.GRID_COL;
    }

    @Override
    public Field<Integer> field4() {
        return HifResults.HIF_RESULTS.GRID_ROW;
    }

    @Override
    public Field<Long> field5() {
        return HifResults.HIF_RESULTS.GRID_CELL_ID;
    }

    @Override
    public Field<BigDecimal> field6() {
        return HifResults.HIF_RESULTS.POPULATION;
    }

    @Override
    public Field<BigDecimal> field7() {
        return HifResults.HIF_RESULTS.DELTA;
    }

    @Override
    public Field<BigDecimal> field8() {
        return HifResults.HIF_RESULTS.RESULT;
    }

    @Override
    public Integer component1() {
        return getHifResultDatasetId();
    }

    @Override
    public Integer component2() {
        return getHifId();
    }

    @Override
    public Integer component3() {
        return getGridCol();
    }

    @Override
    public Integer component4() {
        return getGridRow();
    }

    @Override
    public Long component5() {
        return getGridCellId();
    }

    @Override
    public BigDecimal component6() {
        return getPopulation();
    }

    @Override
    public BigDecimal component7() {
        return getDelta();
    }

    @Override
    public BigDecimal component8() {
        return getResult();
    }

    @Override
    public Integer value1() {
        return getHifResultDatasetId();
    }

    @Override
    public Integer value2() {
        return getHifId();
    }

    @Override
    public Integer value3() {
        return getGridCol();
    }

    @Override
    public Integer value4() {
        return getGridRow();
    }

    @Override
    public Long value5() {
        return getGridCellId();
    }

    @Override
    public BigDecimal value6() {
        return getPopulation();
    }

    @Override
    public BigDecimal value7() {
        return getDelta();
    }

    @Override
    public BigDecimal value8() {
        return getResult();
    }

    @Override
    public HifResultsRecord value1(Integer value) {
        setHifResultDatasetId(value);
        return this;
    }

    @Override
    public HifResultsRecord value2(Integer value) {
        setHifId(value);
        return this;
    }

    @Override
    public HifResultsRecord value3(Integer value) {
        setGridCol(value);
        return this;
    }

    @Override
    public HifResultsRecord value4(Integer value) {
        setGridRow(value);
        return this;
    }

    @Override
    public HifResultsRecord value5(Long value) {
        setGridCellId(value);
        return this;
    }

    @Override
    public HifResultsRecord value6(BigDecimal value) {
        setPopulation(value);
        return this;
    }

    @Override
    public HifResultsRecord value7(BigDecimal value) {
        setDelta(value);
        return this;
    }

    @Override
    public HifResultsRecord value8(BigDecimal value) {
        setResult(value);
        return this;
    }

    @Override
    public HifResultsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Long value5, BigDecimal value6, BigDecimal value7, BigDecimal value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HifResultsRecord
     */
    public HifResultsRecord() {
        super(HifResults.HIF_RESULTS);
    }

    /**
     * Create a detached, initialised HifResultsRecord
     */
    public HifResultsRecord(Integer hifResultDatasetId, Integer hifId, Integer gridCol, Integer gridRow, Long gridCellId, BigDecimal population, BigDecimal delta, BigDecimal result) {
        super(HifResults.HIF_RESULTS);

        setHifResultDatasetId(hifResultDatasetId);
        setHifId(hifId);
        setGridCol(gridCol);
        setGridRow(gridRow);
        setGridCellId(gridCellId);
        setPopulation(population);
        setDelta(delta);
        setResult(result);
    }
}
