/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables.records;


import gov.epa.bencloud.server.database.jooq.tables.HifResult;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HifResultRecord extends TableRecordImpl<HifResultRecord> implements Record9<Integer, Integer, Integer, Integer, Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.hif_result.hif_result_dataset_id</code>.
     */
    public void setHifResultDatasetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.hif_result.hif_result_dataset_id</code>.
     */
    public Integer getHifResultDatasetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.hif_result.hif_id</code>.
     */
    public void setHifId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.hif_result.hif_id</code>.
     */
    public Integer getHifId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.hif_result.grid_col</code>.
     */
    public void setGridCol(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.hif_result.grid_col</code>.
     */
    public Integer getGridCol() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>data.hif_result.grid_row</code>.
     */
    public void setGridRow(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.hif_result.grid_row</code>.
     */
    public Integer getGridRow() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>data.hif_result.grid_cell_id</code>.
     */
    public void setGridCellId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.hif_result.grid_cell_id</code>.
     */
    public Long getGridCellId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>data.hif_result.population</code>.
     */
    public void setPopulation(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>data.hif_result.population</code>.
     */
    public BigDecimal getPopulation() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>data.hif_result.delta</code>.
     */
    public void setDelta(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>data.hif_result.delta</code>.
     */
    public BigDecimal getDelta() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>data.hif_result.result</code>.
     */
    public void setResult(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>data.hif_result.result</code>.
     */
    public BigDecimal getResult() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>data.hif_result.baseline</code>.
     */
    public void setBaseline(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>data.hif_result.baseline</code>.
     */
    public BigDecimal getBaseline() {
        return (BigDecimal) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, Integer, Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Integer, Integer, Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return HifResult.HIF_RESULT.HIF_RESULT_DATASET_ID;
    }

    @Override
    public Field<Integer> field2() {
        return HifResult.HIF_RESULT.HIF_ID;
    }

    @Override
    public Field<Integer> field3() {
        return HifResult.HIF_RESULT.GRID_COL;
    }

    @Override
    public Field<Integer> field4() {
        return HifResult.HIF_RESULT.GRID_ROW;
    }

    @Override
    public Field<Long> field5() {
        return HifResult.HIF_RESULT.GRID_CELL_ID;
    }

    @Override
    public Field<BigDecimal> field6() {
        return HifResult.HIF_RESULT.POPULATION;
    }

    @Override
    public Field<BigDecimal> field7() {
        return HifResult.HIF_RESULT.DELTA;
    }

    @Override
    public Field<BigDecimal> field8() {
        return HifResult.HIF_RESULT.RESULT;
    }

    @Override
    public Field<BigDecimal> field9() {
        return HifResult.HIF_RESULT.BASELINE;
    }

    @Override
    public Integer component1() {
        return getHifResultDatasetId();
    }

    @Override
    public Integer component2() {
        return getHifId();
    }

    @Override
    public Integer component3() {
        return getGridCol();
    }

    @Override
    public Integer component4() {
        return getGridRow();
    }

    @Override
    public Long component5() {
        return getGridCellId();
    }

    @Override
    public BigDecimal component6() {
        return getPopulation();
    }

    @Override
    public BigDecimal component7() {
        return getDelta();
    }

    @Override
    public BigDecimal component8() {
        return getResult();
    }

    @Override
    public BigDecimal component9() {
        return getBaseline();
    }

    @Override
    public Integer value1() {
        return getHifResultDatasetId();
    }

    @Override
    public Integer value2() {
        return getHifId();
    }

    @Override
    public Integer value3() {
        return getGridCol();
    }

    @Override
    public Integer value4() {
        return getGridRow();
    }

    @Override
    public Long value5() {
        return getGridCellId();
    }

    @Override
    public BigDecimal value6() {
        return getPopulation();
    }

    @Override
    public BigDecimal value7() {
        return getDelta();
    }

    @Override
    public BigDecimal value8() {
        return getResult();
    }

    @Override
    public BigDecimal value9() {
        return getBaseline();
    }

    @Override
    public HifResultRecord value1(Integer value) {
        setHifResultDatasetId(value);
        return this;
    }

    @Override
    public HifResultRecord value2(Integer value) {
        setHifId(value);
        return this;
    }

    @Override
    public HifResultRecord value3(Integer value) {
        setGridCol(value);
        return this;
    }

    @Override
    public HifResultRecord value4(Integer value) {
        setGridRow(value);
        return this;
    }

    @Override
    public HifResultRecord value5(Long value) {
        setGridCellId(value);
        return this;
    }

    @Override
    public HifResultRecord value6(BigDecimal value) {
        setPopulation(value);
        return this;
    }

    @Override
    public HifResultRecord value7(BigDecimal value) {
        setDelta(value);
        return this;
    }

    @Override
    public HifResultRecord value8(BigDecimal value) {
        setResult(value);
        return this;
    }

    @Override
    public HifResultRecord value9(BigDecimal value) {
        setBaseline(value);
        return this;
    }

    @Override
    public HifResultRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Long value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, BigDecimal value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HifResultRecord
     */
    public HifResultRecord() {
        super(HifResult.HIF_RESULT);
    }

    /**
     * Create a detached, initialised HifResultRecord
     */
    public HifResultRecord(Integer hifResultDatasetId, Integer hifId, Integer gridCol, Integer gridRow, Long gridCellId, BigDecimal population, BigDecimal delta, BigDecimal result, BigDecimal baseline) {
        super(HifResult.HIF_RESULT);

        setHifResultDatasetId(hifResultDatasetId);
        setHifId(hifId);
        setGridCol(gridCol);
        setGridRow(gridRow);
        setGridCellId(gridCellId);
        setPopulation(population);
        setDelta(delta);
        setResult(result);
        setBaseline(baseline);
    }
}
