/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables.records;


import gov.epa.bencloud.server.database.jooq.tables.IncidenceValue;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IncidenceValueRecord extends TableRecordImpl<IncidenceValueRecord> implements Record4<Integer, Integer, Integer, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.incidence_value.incidence_rate_id</code>.
     */
    public void setIncidenceRateId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.incidence_value.incidence_rate_id</code>.
     */
    public Integer getIncidenceRateId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.incidence_value.grid_col</code>.
     */
    public void setGridCol(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.incidence_value.grid_col</code>.
     */
    public Integer getGridCol() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.incidence_value.grid_row</code>.
     */
    public void setGridRow(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.incidence_value.grid_row</code>.
     */
    public Integer getGridRow() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>data.incidence_value.value</code>.
     */
    public void setValue(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.incidence_value.value</code>.
     */
    public BigDecimal getValue() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return IncidenceValue.INCIDENCE_VALUE.INCIDENCE_RATE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return IncidenceValue.INCIDENCE_VALUE.GRID_COL;
    }

    @Override
    public Field<Integer> field3() {
        return IncidenceValue.INCIDENCE_VALUE.GRID_ROW;
    }

    @Override
    public Field<BigDecimal> field4() {
        return IncidenceValue.INCIDENCE_VALUE.VALUE;
    }

    @Override
    public Integer component1() {
        return getIncidenceRateId();
    }

    @Override
    public Integer component2() {
        return getGridCol();
    }

    @Override
    public Integer component3() {
        return getGridRow();
    }

    @Override
    public BigDecimal component4() {
        return getValue();
    }

    @Override
    public Integer value1() {
        return getIncidenceRateId();
    }

    @Override
    public Integer value2() {
        return getGridCol();
    }

    @Override
    public Integer value3() {
        return getGridRow();
    }

    @Override
    public BigDecimal value4() {
        return getValue();
    }

    @Override
    public IncidenceValueRecord value1(Integer value) {
        setIncidenceRateId(value);
        return this;
    }

    @Override
    public IncidenceValueRecord value2(Integer value) {
        setGridCol(value);
        return this;
    }

    @Override
    public IncidenceValueRecord value3(Integer value) {
        setGridRow(value);
        return this;
    }

    @Override
    public IncidenceValueRecord value4(BigDecimal value) {
        setValue(value);
        return this;
    }

    @Override
    public IncidenceValueRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IncidenceValueRecord
     */
    public IncidenceValueRecord() {
        super(IncidenceValue.INCIDENCE_VALUE);
    }

    /**
     * Create a detached, initialised IncidenceValueRecord
     */
    public IncidenceValueRecord(Integer incidenceRateId, Integer gridCol, Integer gridRow, BigDecimal value) {
        super(IncidenceValue.INCIDENCE_VALUE);

        setIncidenceRateId(incidenceRateId);
        setGridCol(gridCol);
        setGridRow(gridRow);
        setValue(value);
    }
}
