/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables.records;


import gov.epa.bencloud.server.database.jooq.tables.IncomeGrowthAdjFactor;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IncomeGrowthAdjFactorRecord extends UpdatableRecordImpl<IncomeGrowthAdjFactorRecord> implements Record5<Integer, Short, Short, BigDecimal, Short> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.income_growth_adj_factor.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.income_growth_adj_factor.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.income_growth_adj_factor.income_growth_adj_dataset_id</code>.
     */
    public void setIncomeGrowthAdjDatasetId(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.income_growth_adj_factor.income_growth_adj_dataset_id</code>.
     */
    public Short getIncomeGrowthAdjDatasetId() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>data.income_growth_adj_factor.growth_year</code>.
     */
    public void setGrowthYear(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.income_growth_adj_factor.growth_year</code>.
     */
    public Short getGrowthYear() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>data.income_growth_adj_factor.mean_value</code>.
     */
    public void setMeanValue(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.income_growth_adj_factor.mean_value</code>.
     */
    public BigDecimal getMeanValue() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>data.income_growth_adj_factor.endpoint_group_id</code>.
     */
    public void setEndpointGroupId(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.income_growth_adj_factor.endpoint_group_id</code>.
     */
    public Short getEndpointGroupId() {
        return (Short) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Short, Short, BigDecimal, Short> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Short, Short, BigDecimal, Short> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return IncomeGrowthAdjFactor.INCOME_GROWTH_ADJ_FACTOR.ID;
    }

    @Override
    public Field<Short> field2() {
        return IncomeGrowthAdjFactor.INCOME_GROWTH_ADJ_FACTOR.INCOME_GROWTH_ADJ_DATASET_ID;
    }

    @Override
    public Field<Short> field3() {
        return IncomeGrowthAdjFactor.INCOME_GROWTH_ADJ_FACTOR.GROWTH_YEAR;
    }

    @Override
    public Field<BigDecimal> field4() {
        return IncomeGrowthAdjFactor.INCOME_GROWTH_ADJ_FACTOR.MEAN_VALUE;
    }

    @Override
    public Field<Short> field5() {
        return IncomeGrowthAdjFactor.INCOME_GROWTH_ADJ_FACTOR.ENDPOINT_GROUP_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Short component2() {
        return getIncomeGrowthAdjDatasetId();
    }

    @Override
    public Short component3() {
        return getGrowthYear();
    }

    @Override
    public BigDecimal component4() {
        return getMeanValue();
    }

    @Override
    public Short component5() {
        return getEndpointGroupId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Short value2() {
        return getIncomeGrowthAdjDatasetId();
    }

    @Override
    public Short value3() {
        return getGrowthYear();
    }

    @Override
    public BigDecimal value4() {
        return getMeanValue();
    }

    @Override
    public Short value5() {
        return getEndpointGroupId();
    }

    @Override
    public IncomeGrowthAdjFactorRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public IncomeGrowthAdjFactorRecord value2(Short value) {
        setIncomeGrowthAdjDatasetId(value);
        return this;
    }

    @Override
    public IncomeGrowthAdjFactorRecord value3(Short value) {
        setGrowthYear(value);
        return this;
    }

    @Override
    public IncomeGrowthAdjFactorRecord value4(BigDecimal value) {
        setMeanValue(value);
        return this;
    }

    @Override
    public IncomeGrowthAdjFactorRecord value5(Short value) {
        setEndpointGroupId(value);
        return this;
    }

    @Override
    public IncomeGrowthAdjFactorRecord values(Integer value1, Short value2, Short value3, BigDecimal value4, Short value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IncomeGrowthAdjFactorRecord
     */
    public IncomeGrowthAdjFactorRecord() {
        super(IncomeGrowthAdjFactor.INCOME_GROWTH_ADJ_FACTOR);
    }

    /**
     * Create a detached, initialised IncomeGrowthAdjFactorRecord
     */
    public IncomeGrowthAdjFactorRecord(Integer id, Short incomeGrowthAdjDatasetId, Short growthYear, BigDecimal meanValue, Short endpointGroupId) {
        super(IncomeGrowthAdjFactor.INCOME_GROWTH_ADJ_FACTOR);

        setId(id);
        setIncomeGrowthAdjDatasetId(incomeGrowthAdjDatasetId);
        setGrowthYear(growthYear);
        setMeanValue(meanValue);
        setEndpointGroupId(endpointGroupId);
    }
}
