/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables.records;


import gov.epa.bencloud.server.database.jooq.tables.InflationEntry;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InflationEntryRecord extends TableRecordImpl<InflationEntryRecord> implements Record5<Integer, Integer, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>data.inflation_entry.inflation_dataset_id</code>.
     */
    public void setInflationDatasetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>data.inflation_entry.inflation_dataset_id</code>.
     */
    public Integer getInflationDatasetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>data.inflation_entry.entry_year</code>.
     */
    public void setEntryYear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>data.inflation_entry.entry_year</code>.
     */
    public Integer getEntryYear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>data.inflation_entry.all_goods_index</code>.
     */
    public void setAllGoodsIndex(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>data.inflation_entry.all_goods_index</code>.
     */
    public BigDecimal getAllGoodsIndex() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>data.inflation_entry.medical_cost_index</code>.
     */
    public void setMedicalCostIndex(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>data.inflation_entry.medical_cost_index</code>.
     */
    public BigDecimal getMedicalCostIndex() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>data.inflation_entry.wage_index</code>.
     */
    public void setWageIndex(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>data.inflation_entry.wage_index</code>.
     */
    public BigDecimal getWageIndex() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return InflationEntry.INFLATION_ENTRY.INFLATION_DATASET_ID;
    }

    @Override
    public Field<Integer> field2() {
        return InflationEntry.INFLATION_ENTRY.ENTRY_YEAR;
    }

    @Override
    public Field<BigDecimal> field3() {
        return InflationEntry.INFLATION_ENTRY.ALL_GOODS_INDEX;
    }

    @Override
    public Field<BigDecimal> field4() {
        return InflationEntry.INFLATION_ENTRY.MEDICAL_COST_INDEX;
    }

    @Override
    public Field<BigDecimal> field5() {
        return InflationEntry.INFLATION_ENTRY.WAGE_INDEX;
    }

    @Override
    public Integer component1() {
        return getInflationDatasetId();
    }

    @Override
    public Integer component2() {
        return getEntryYear();
    }

    @Override
    public BigDecimal component3() {
        return getAllGoodsIndex();
    }

    @Override
    public BigDecimal component4() {
        return getMedicalCostIndex();
    }

    @Override
    public BigDecimal component5() {
        return getWageIndex();
    }

    @Override
    public Integer value1() {
        return getInflationDatasetId();
    }

    @Override
    public Integer value2() {
        return getEntryYear();
    }

    @Override
    public BigDecimal value3() {
        return getAllGoodsIndex();
    }

    @Override
    public BigDecimal value4() {
        return getMedicalCostIndex();
    }

    @Override
    public BigDecimal value5() {
        return getWageIndex();
    }

    @Override
    public InflationEntryRecord value1(Integer value) {
        setInflationDatasetId(value);
        return this;
    }

    @Override
    public InflationEntryRecord value2(Integer value) {
        setEntryYear(value);
        return this;
    }

    @Override
    public InflationEntryRecord value3(BigDecimal value) {
        setAllGoodsIndex(value);
        return this;
    }

    @Override
    public InflationEntryRecord value4(BigDecimal value) {
        setMedicalCostIndex(value);
        return this;
    }

    @Override
    public InflationEntryRecord value5(BigDecimal value) {
        setWageIndex(value);
        return this;
    }

    @Override
    public InflationEntryRecord values(Integer value1, Integer value2, BigDecimal value3, BigDecimal value4, BigDecimal value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InflationEntryRecord
     */
    public InflationEntryRecord() {
        super(InflationEntry.INFLATION_ENTRY);
    }

    /**
     * Create a detached, initialised InflationEntryRecord
     */
    public InflationEntryRecord(Integer inflationDatasetId, Integer entryYear, BigDecimal allGoodsIndex, BigDecimal medicalCostIndex, BigDecimal wageIndex) {
        super(InflationEntry.INFLATION_ENTRY);

        setInflationDatasetId(inflationDatasetId);
        setEntryYear(entryYear);
        setAllGoodsIndex(allGoodsIndex);
        setMedicalCostIndex(medicalCostIndex);
        setWageIndex(wageIndex);
    }
}
