/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.grids.tables.records;


import gov.epa.bencloud.server.database.jooq.grids.tables.UsCounty;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsCountyRecord extends UpdatableRecordImpl<UsCountyRecord> implements Record9<Integer, String, String, String, String, String, Short, Short, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>grids.us_county.gid</code>.
     */
    public void setGid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>grids.us_county.gid</code>.
     */
    public Integer getGid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>grids.us_county.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>grids.us_county.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>grids.us_county.state_name</code>.
     */
    public void setStateName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>grids.us_county.state_name</code>.
     */
    public String getStateName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>grids.us_county.state_fips</code>.
     */
    public void setStateFips(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>grids.us_county.state_fips</code>.
     */
    public String getStateFips() {
        return (String) get(3);
    }

    /**
     * Setter for <code>grids.us_county.cnty_fips</code>.
     */
    public void setCntyFips(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>grids.us_county.cnty_fips</code>.
     */
    public String getCntyFips() {
        return (String) get(4);
    }

    /**
     * Setter for <code>grids.us_county.fips</code>.
     */
    public void setFips(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>grids.us_county.fips</code>.
     */
    public String getFips() {
        return (String) get(5);
    }

    /**
     * Setter for <code>grids.us_county.col</code>.
     */
    public void setCol(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>grids.us_county.col</code>.
     */
    public Short getCol() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>grids.us_county.row</code>.
     */
    public void setRow(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>grids.us_county.row</code>.
     */
    public Short getRow() {
        return (Short) get(7);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setGeom(Object value) {
        set(8, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getGeom() {
        return get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, String, String, Short, Short, Object> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, String, String, String, Short, Short, Object> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UsCounty.US_COUNTY.GID;
    }

    @Override
    public Field<String> field2() {
        return UsCounty.US_COUNTY.NAME;
    }

    @Override
    public Field<String> field3() {
        return UsCounty.US_COUNTY.STATE_NAME;
    }

    @Override
    public Field<String> field4() {
        return UsCounty.US_COUNTY.STATE_FIPS;
    }

    @Override
    public Field<String> field5() {
        return UsCounty.US_COUNTY.CNTY_FIPS;
    }

    @Override
    public Field<String> field6() {
        return UsCounty.US_COUNTY.FIPS;
    }

    @Override
    public Field<Short> field7() {
        return UsCounty.US_COUNTY.COL;
    }

    @Override
    public Field<Short> field8() {
        return UsCounty.US_COUNTY.ROW;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field9() {
        return UsCounty.US_COUNTY.GEOM;
    }

    @Override
    public Integer component1() {
        return getGid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getStateName();
    }

    @Override
    public String component4() {
        return getStateFips();
    }

    @Override
    public String component5() {
        return getCntyFips();
    }

    @Override
    public String component6() {
        return getFips();
    }

    @Override
    public Short component7() {
        return getCol();
    }

    @Override
    public Short component8() {
        return getRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component9() {
        return getGeom();
    }

    @Override
    public Integer value1() {
        return getGid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getStateName();
    }

    @Override
    public String value4() {
        return getStateFips();
    }

    @Override
    public String value5() {
        return getCntyFips();
    }

    @Override
    public String value6() {
        return getFips();
    }

    @Override
    public Short value7() {
        return getCol();
    }

    @Override
    public Short value8() {
        return getRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value9() {
        return getGeom();
    }

    @Override
    public UsCountyRecord value1(Integer value) {
        setGid(value);
        return this;
    }

    @Override
    public UsCountyRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UsCountyRecord value3(String value) {
        setStateName(value);
        return this;
    }

    @Override
    public UsCountyRecord value4(String value) {
        setStateFips(value);
        return this;
    }

    @Override
    public UsCountyRecord value5(String value) {
        setCntyFips(value);
        return this;
    }

    @Override
    public UsCountyRecord value6(String value) {
        setFips(value);
        return this;
    }

    @Override
    public UsCountyRecord value7(Short value) {
        setCol(value);
        return this;
    }

    @Override
    public UsCountyRecord value8(Short value) {
        setRow(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public UsCountyRecord value9(Object value) {
        setGeom(value);
        return this;
    }

    @Override
    public UsCountyRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Short value7, Short value8, Object value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsCountyRecord
     */
    public UsCountyRecord() {
        super(UsCounty.US_COUNTY);
    }

    /**
     * Create a detached, initialised UsCountyRecord
     */
    public UsCountyRecord(Integer gid, String name, String stateName, String stateFips, String cntyFips, String fips, Short col, Short row, Object geom) {
        super(UsCounty.US_COUNTY);

        setGid(gid);
        setName(name);
        setStateName(stateName);
        setStateFips(stateFips);
        setCntyFips(cntyFips);
        setFips(fips);
        setCol(col);
        setRow(row);
        setGeom(geom);
    }
}
