/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables;


import gov.epa.bencloud.server.database.jooq.data.Data;
import gov.epa.bencloud.server.database.jooq.data.Keys;
import gov.epa.bencloud.server.database.jooq.data.tables.records.GenderRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gender extends TableImpl<GenderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>data.gender</code>
     */
    public static final Gender GENDER = new Gender();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GenderRecord> getRecordType() {
        return GenderRecord.class;
    }

    /**
     * The column <code>data.gender.id</code>.
     */
    public final TableField<GenderRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>data.gender.name</code>.
     */
    public final TableField<GenderRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    private Gender(Name alias, Table<GenderRecord> aliased) {
        this(alias, aliased, null);
    }

    private Gender(Name alias, Table<GenderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>data.gender</code> table reference
     */
    public Gender(String alias) {
        this(DSL.name(alias), GENDER);
    }

    /**
     * Create an aliased <code>data.gender</code> table reference
     */
    public Gender(Name alias) {
        this(alias, GENDER);
    }

    /**
     * Create a <code>data.gender</code> table reference
     */
    public Gender() {
        this(DSL.name("gender"), null);
    }

    public <O extends Record> Gender(Table<O> child, ForeignKey<O, GenderRecord> key) {
        super(child, key, GENDER);
    }

    @Override
    public Schema getSchema() {
        return Data.DATA;
    }

    @Override
    public Identity<GenderRecord, Integer> getIdentity() {
        return (Identity<GenderRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GenderRecord> getPrimaryKey() {
        return Keys.GENDER_PKEY;
    }

    @Override
    public List<UniqueKey<GenderRecord>> getKeys() {
        return Arrays.<UniqueKey<GenderRecord>>asList(Keys.GENDER_PKEY);
    }

    @Override
    public Gender as(String alias) {
        return new Gender(DSL.name(alias), this);
    }

    @Override
    public Gender as(Name alias) {
        return new Gender(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gender rename(String name) {
        return new Gender(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gender rename(Name name) {
        return new Gender(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
