/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.data.tables;


import gov.epa.bencloud.server.database.jooq.data.Data;
import gov.epa.bencloud.server.database.jooq.data.Keys;
import gov.epa.bencloud.server.database.jooq.data.tables.records.SeasonalMetricRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeasonalMetric extends TableImpl<SeasonalMetricRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>data.seasonal_metric</code>
     */
    public static final SeasonalMetric SEASONAL_METRIC = new SeasonalMetric();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeasonalMetricRecord> getRecordType() {
        return SeasonalMetricRecord.class;
    }

    /**
     * The column <code>data.seasonal_metric.id</code>.
     */
    public final TableField<SeasonalMetricRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>data.seasonal_metric.metric_id</code>.
     */
    public final TableField<SeasonalMetricRecord, Integer> METRIC_ID = createField(DSL.name("metric_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>data.seasonal_metric.name</code>.
     */
    public final TableField<SeasonalMetricRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    private SeasonalMetric(Name alias, Table<SeasonalMetricRecord> aliased) {
        this(alias, aliased, null);
    }

    private SeasonalMetric(Name alias, Table<SeasonalMetricRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>data.seasonal_metric</code> table reference
     */
    public SeasonalMetric(String alias) {
        this(DSL.name(alias), SEASONAL_METRIC);
    }

    /**
     * Create an aliased <code>data.seasonal_metric</code> table reference
     */
    public SeasonalMetric(Name alias) {
        this(alias, SEASONAL_METRIC);
    }

    /**
     * Create a <code>data.seasonal_metric</code> table reference
     */
    public SeasonalMetric() {
        this(DSL.name("seasonal_metric"), null);
    }

    public <O extends Record> SeasonalMetric(Table<O> child, ForeignKey<O, SeasonalMetricRecord> key) {
        super(child, key, SEASONAL_METRIC);
    }

    @Override
    public Schema getSchema() {
        return Data.DATA;
    }

    @Override
    public Identity<SeasonalMetricRecord, Integer> getIdentity() {
        return (Identity<SeasonalMetricRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SeasonalMetricRecord> getPrimaryKey() {
        return Keys.SEASONAL_METRIC_PKEY;
    }

    @Override
    public List<UniqueKey<SeasonalMetricRecord>> getKeys() {
        return Arrays.<UniqueKey<SeasonalMetricRecord>>asList(Keys.SEASONAL_METRIC_PKEY);
    }

    @Override
    public List<ForeignKey<SeasonalMetricRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SeasonalMetricRecord, ?>>asList(Keys.SEASONAL_METRIC__SEASONAL_METRIC_METRIC_ID_FKEY);
    }

    private transient PollutantMetric _pollutantMetric;

    public PollutantMetric pollutantMetric() {
        if (_pollutantMetric == null)
            _pollutantMetric = new PollutantMetric(this, Keys.SEASONAL_METRIC__SEASONAL_METRIC_METRIC_ID_FKEY);

        return _pollutantMetric;
    }

    @Override
    public SeasonalMetric as(String alias) {
        return new SeasonalMetric(DSL.name(alias), this);
    }

    @Override
    public SeasonalMetric as(Name alias) {
        return new SeasonalMetric(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SeasonalMetric rename(String name) {
        return new SeasonalMetric(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SeasonalMetric rename(Name name) {
        return new SeasonalMetric(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
