export default function () {
  return {
    pollutantFriendlyName: "",
    pollutantName: "",
    pollutantId: null,
    incidenceId: -1,
    incidenceName: "",
    populationDatasetId: null,
    populationDatasetName: "",
    populationYearsSelected: [],
    populationYears: [],
    healthEffects: [],
    healthImpactFunctions: [],
    prePolicyAirQualityId: null,
    prePolicyAirQualityName: "",
    prePolicyGridDefinitionId: [],
    prePolicyGridDefinitionName: "",
    prePolicyAirQualityMetricId: null,
    postPolicyAirQualityId: [],
    postPolicyAirQualityName: [],
    postPolicyGridDefinitionId: [],
    postPolicyGridDefinitionName: [],
    postPolicyAirQualitySelection: null,
    postPolicyAirQualityMetricId: [],
    valuationsForHealthImpactFunctionGroups: [],
    location,
    limitToGridId: null,
    airQualityLayers: null,
    stepNumber: 1,
    aggregationScale: null,
    applyYearsToAll: false,
    batchTaskObject: null,
    valuationSelection: "Select my own value functions",
    hifResultColumns: "ages,study,qualifier,delta_aq,point_estimate,population,baseline",
  }
}
