/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables;


import gov.epa.bencloud.server.database.jooq.Data;
import gov.epa.bencloud.server.database.jooq.Keys;
import gov.epa.bencloud.server.database.jooq.tables.records.HifResultDatasetRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HifResultDataset extends TableImpl<HifResultDatasetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>data.hif_result_dataset</code>
     */
    public static final HifResultDataset HIF_RESULT_DATASET = new HifResultDataset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HifResultDatasetRecord> getRecordType() {
        return HifResultDatasetRecord.class;
    }

    /**
     * The column <code>data.hif_result_dataset.id</code>.
     */
    public final TableField<HifResultDatasetRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>data.hif_result_dataset.task_uuid</code>.
     */
    public final TableField<HifResultDatasetRecord, String> TASK_UUID = createField(DSL.name("task_uuid"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>data.hif_result_dataset.name</code>.
     */
    public final TableField<HifResultDatasetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>data.hif_result_dataset.population_dataset_id</code>.
     */
    public final TableField<HifResultDatasetRecord, Integer> POPULATION_DATASET_ID = createField(DSL.name("population_dataset_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>data.hif_result_dataset.population_year</code>.
     */
    public final TableField<HifResultDatasetRecord, Integer> POPULATION_YEAR = createField(DSL.name("population_year"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>data.hif_result_dataset.baseline_aq_layer_id</code>.
     */
    public final TableField<HifResultDatasetRecord, Integer> BASELINE_AQ_LAYER_ID = createField(DSL.name("baseline_aq_layer_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>data.hif_result_dataset.scenario_aq_layer_id</code>.
     */
    public final TableField<HifResultDatasetRecord, Integer> SCENARIO_AQ_LAYER_ID = createField(DSL.name("scenario_aq_layer_id"), SQLDataType.INTEGER, this, "");

    private HifResultDataset(Name alias, Table<HifResultDatasetRecord> aliased) {
        this(alias, aliased, null);
    }

    private HifResultDataset(Name alias, Table<HifResultDatasetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>data.hif_result_dataset</code> table reference
     */
    public HifResultDataset(String alias) {
        this(DSL.name(alias), HIF_RESULT_DATASET);
    }

    /**
     * Create an aliased <code>data.hif_result_dataset</code> table reference
     */
    public HifResultDataset(Name alias) {
        this(alias, HIF_RESULT_DATASET);
    }

    /**
     * Create a <code>data.hif_result_dataset</code> table reference
     */
    public HifResultDataset() {
        this(DSL.name("hif_result_dataset"), null);
    }

    public <O extends Record> HifResultDataset(Table<O> child, ForeignKey<O, HifResultDatasetRecord> key) {
        super(child, key, HIF_RESULT_DATASET);
    }

    @Override
    public Schema getSchema() {
        return Data.DATA;
    }

    @Override
    public Identity<HifResultDatasetRecord, Integer> getIdentity() {
        return (Identity<HifResultDatasetRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HifResultDatasetRecord> getPrimaryKey() {
        return Keys.HIF_RESULT_DATASET_PKEY;
    }

    @Override
    public List<UniqueKey<HifResultDatasetRecord>> getKeys() {
        return Arrays.<UniqueKey<HifResultDatasetRecord>>asList(Keys.HIF_RESULT_DATASET_PKEY);
    }

    @Override
    public HifResultDataset as(String alias) {
        return new HifResultDataset(DSL.name(alias), this);
    }

    @Override
    public HifResultDataset as(Name alias) {
        return new HifResultDataset(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HifResultDataset rename(String name) {
        return new HifResultDataset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HifResultDataset rename(Name name) {
        return new HifResultDataset(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
