/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables;


import gov.epa.bencloud.server.database.jooq.Data;
import gov.epa.bencloud.server.database.jooq.Keys;
import gov.epa.bencloud.server.database.jooq.tables.records.PopConfigRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PopConfig extends TableImpl<PopConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>data.pop_config</code>
     */
    public static final PopConfig POP_CONFIG = new PopConfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PopConfigRecord> getRecordType() {
        return PopConfigRecord.class;
    }

    /**
     * The column <code>data.pop_config.id</code>.
     */
    public final TableField<PopConfigRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>data.pop_config.name</code>.
     */
    public final TableField<PopConfigRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private PopConfig(Name alias, Table<PopConfigRecord> aliased) {
        this(alias, aliased, null);
    }

    private PopConfig(Name alias, Table<PopConfigRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>data.pop_config</code> table reference
     */
    public PopConfig(String alias) {
        this(DSL.name(alias), POP_CONFIG);
    }

    /**
     * Create an aliased <code>data.pop_config</code> table reference
     */
    public PopConfig(Name alias) {
        this(alias, POP_CONFIG);
    }

    /**
     * Create a <code>data.pop_config</code> table reference
     */
    public PopConfig() {
        this(DSL.name("pop_config"), null);
    }

    public <O extends Record> PopConfig(Table<O> child, ForeignKey<O, PopConfigRecord> key) {
        super(child, key, POP_CONFIG);
    }

    @Override
    public Schema getSchema() {
        return Data.DATA;
    }

    @Override
    public Identity<PopConfigRecord, Integer> getIdentity() {
        return (Identity<PopConfigRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PopConfigRecord> getPrimaryKey() {
        return Keys.POP_CONFIG_PKEY;
    }

    @Override
    public List<UniqueKey<PopConfigRecord>> getKeys() {
        return Arrays.<UniqueKey<PopConfigRecord>>asList(Keys.POP_CONFIG_PKEY);
    }

    @Override
    public PopConfig as(String alias) {
        return new PopConfig(DSL.name(alias), this);
    }

    @Override
    public PopConfig as(Name alias) {
        return new PopConfig(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PopConfig rename(String name) {
        return new PopConfig(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PopConfig rename(Name name) {
        return new PopConfig(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
