/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables;


import gov.epa.bencloud.server.database.jooq.Data;
import gov.epa.bencloud.server.database.jooq.tables.records.PopulationYearRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PopulationYear extends TableImpl<PopulationYearRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>data.population_year</code>
     */
    public static final PopulationYear POPULATION_YEAR = new PopulationYear();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PopulationYearRecord> getRecordType() {
        return PopulationYearRecord.class;
    }

    /**
     * The column <code>data.population_year.population_dataset_id</code>.
     */
    public final TableField<PopulationYearRecord, Integer> POPULATION_DATASET_ID = createField(DSL.name("population_dataset_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>data.population_year.pop_year</code>.
     */
    public final TableField<PopulationYearRecord, Integer> POP_YEAR = createField(DSL.name("pop_year"), SQLDataType.INTEGER, this, "");

    private PopulationYear(Name alias, Table<PopulationYearRecord> aliased) {
        this(alias, aliased, null);
    }

    private PopulationYear(Name alias, Table<PopulationYearRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>data.population_year</code> table reference
     */
    public PopulationYear(String alias) {
        this(DSL.name(alias), POPULATION_YEAR);
    }

    /**
     * Create an aliased <code>data.population_year</code> table reference
     */
    public PopulationYear(Name alias) {
        this(alias, POPULATION_YEAR);
    }

    /**
     * Create a <code>data.population_year</code> table reference
     */
    public PopulationYear() {
        this(DSL.name("population_year"), null);
    }

    public <O extends Record> PopulationYear(Table<O> child, ForeignKey<O, PopulationYearRecord> key) {
        super(child, key, POPULATION_YEAR);
    }

    @Override
    public Schema getSchema() {
        return Data.DATA;
    }

    @Override
    public PopulationYear as(String alias) {
        return new PopulationYear(DSL.name(alias), this);
    }

    @Override
    public PopulationYear as(Name alias) {
        return new PopulationYear(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PopulationYear rename(String name) {
        return new PopulationYear(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PopulationYear rename(Name name) {
        return new PopulationYear(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
