/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables;


import gov.epa.bencloud.server.database.jooq.Data;
import gov.epa.bencloud.server.database.jooq.Indexes;
import gov.epa.bencloud.server.database.jooq.tables.records.TaskCompleteRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskComplete extends TableImpl<TaskCompleteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>data.task_complete</code>
     */
    public static final TaskComplete TASK_COMPLETE = new TaskComplete();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskCompleteRecord> getRecordType() {
        return TaskCompleteRecord.class;
    }

    /**
     * The column <code>data.task_complete.id</code>.
     */
    public final TableField<TaskCompleteRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>data.task_complete.task_uuid</code>.
     */
    public final TableField<TaskCompleteRecord, String> TASK_UUID = createField(DSL.name("task_uuid"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>data.task_complete.user_identifier</code>.
     */
    public final TableField<TaskCompleteRecord, String> USER_IDENTIFIER = createField(DSL.name("user_identifier"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>data.task_complete.priority</code>.
     */
    public final TableField<TaskCompleteRecord, Integer> PRIORITY = createField(DSL.name("priority"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>data.task_complete.task_name</code>.
     */
    public final TableField<TaskCompleteRecord, String> TASK_NAME = createField(DSL.name("task_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>data.task_complete.task_description</code>.
     */
    public final TableField<TaskCompleteRecord, String> TASK_DESCRIPTION = createField(DSL.name("task_description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>data.task_complete.task_results</code>.
     */
    public final TableField<TaskCompleteRecord, String> TASK_RESULTS = createField(DSL.name("task_results"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>data.task_complete.submitted_date</code>.
     */
    public final TableField<TaskCompleteRecord, LocalDateTime> SUBMITTED_DATE = createField(DSL.name("submitted_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>data.task_complete.completed_date</code>.
     */
    public final TableField<TaskCompleteRecord, LocalDateTime> COMPLETED_DATE = createField(DSL.name("completed_date"), SQLDataType.LOCALDATETIME(6), this, "");

    private TaskComplete(Name alias, Table<TaskCompleteRecord> aliased) {
        this(alias, aliased, null);
    }

    private TaskComplete(Name alias, Table<TaskCompleteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>data.task_complete</code> table reference
     */
    public TaskComplete(String alias) {
        this(DSL.name(alias), TASK_COMPLETE);
    }

    /**
     * Create an aliased <code>data.task_complete</code> table reference
     */
    public TaskComplete(Name alias) {
        this(alias, TASK_COMPLETE);
    }

    /**
     * Create a <code>data.task_complete</code> table reference
     */
    public TaskComplete() {
        this(DSL.name("task_complete"), null);
    }

    public <O extends Record> TaskComplete(Table<O> child, ForeignKey<O, TaskCompleteRecord> key) {
        super(child, key, TASK_COMPLETE);
    }

    @Override
    public Schema getSchema() {
        return Data.DATA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TASK_COMPLETE_BY_DATE, Indexes.TASK_COMPLETE_BY_UUID);
    }

    @Override
    public Identity<TaskCompleteRecord, Integer> getIdentity() {
        return (Identity<TaskCompleteRecord, Integer>) super.getIdentity();
    }

    @Override
    public TaskComplete as(String alias) {
        return new TaskComplete(DSL.name(alias), this);
    }

    @Override
    public TaskComplete as(Name alias) {
        return new TaskComplete(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskComplete rename(String name) {
        return new TaskComplete(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskComplete rename(Name name) {
        return new TaskComplete(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
