/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables;


import gov.epa.bencloud.server.database.jooq.Data;
import gov.epa.bencloud.server.database.jooq.Keys;
import gov.epa.bencloud.server.database.jooq.tables.records.ValuationFunctionDatasetRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValuationFunctionDataset extends TableImpl<ValuationFunctionDatasetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>data.valuation_function_dataset</code>
     */
    public static final ValuationFunctionDataset VALUATION_FUNCTION_DATASET = new ValuationFunctionDataset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ValuationFunctionDatasetRecord> getRecordType() {
        return ValuationFunctionDatasetRecord.class;
    }

    /**
     * The column <code>data.valuation_function_dataset.id</code>.
     */
    public final TableField<ValuationFunctionDatasetRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>data.valuation_function_dataset.name</code>.
     */
    public final TableField<ValuationFunctionDatasetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private ValuationFunctionDataset(Name alias, Table<ValuationFunctionDatasetRecord> aliased) {
        this(alias, aliased, null);
    }

    private ValuationFunctionDataset(Name alias, Table<ValuationFunctionDatasetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>data.valuation_function_dataset</code> table reference
     */
    public ValuationFunctionDataset(String alias) {
        this(DSL.name(alias), VALUATION_FUNCTION_DATASET);
    }

    /**
     * Create an aliased <code>data.valuation_function_dataset</code> table reference
     */
    public ValuationFunctionDataset(Name alias) {
        this(alias, VALUATION_FUNCTION_DATASET);
    }

    /**
     * Create a <code>data.valuation_function_dataset</code> table reference
     */
    public ValuationFunctionDataset() {
        this(DSL.name("valuation_function_dataset"), null);
    }

    public <O extends Record> ValuationFunctionDataset(Table<O> child, ForeignKey<O, ValuationFunctionDatasetRecord> key) {
        super(child, key, VALUATION_FUNCTION_DATASET);
    }

    @Override
    public Schema getSchema() {
        return Data.DATA;
    }

    @Override
    public Identity<ValuationFunctionDatasetRecord, Integer> getIdentity() {
        return (Identity<ValuationFunctionDatasetRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ValuationFunctionDatasetRecord> getPrimaryKey() {
        return Keys.VALUATION_FUNCTION_DATASET_PKEY;
    }

    @Override
    public List<UniqueKey<ValuationFunctionDatasetRecord>> getKeys() {
        return Arrays.<UniqueKey<ValuationFunctionDatasetRecord>>asList(Keys.VALUATION_FUNCTION_DATASET_PKEY);
    }

    @Override
    public ValuationFunctionDataset as(String alias) {
        return new ValuationFunctionDataset(DSL.name(alias), this);
    }

    @Override
    public ValuationFunctionDataset as(Name alias) {
        return new ValuationFunctionDataset(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ValuationFunctionDataset rename(String name) {
        return new ValuationFunctionDataset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ValuationFunctionDataset rename(Name name) {
        return new ValuationFunctionDataset(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
