/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.tables;


import gov.epa.bencloud.server.database.jooq.Data;
import gov.epa.bencloud.server.database.jooq.Keys;
import gov.epa.bencloud.server.database.jooq.tables.records.ValuationResultDatasetRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValuationResultDataset extends TableImpl<ValuationResultDatasetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>data.valuation_result_dataset</code>
     */
    public static final ValuationResultDataset VALUATION_RESULT_DATASET = new ValuationResultDataset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ValuationResultDatasetRecord> getRecordType() {
        return ValuationResultDatasetRecord.class;
    }

    /**
     * The column <code>data.valuation_result_dataset.id</code>.
     */
    public final TableField<ValuationResultDatasetRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>data.valuation_result_dataset.task_uuid</code>.
     */
    public final TableField<ValuationResultDatasetRecord, String> TASK_UUID = createField(DSL.name("task_uuid"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>data.valuation_result_dataset.name</code>.
     */
    public final TableField<ValuationResultDatasetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>data.valuation_result_dataset.variable_dataset_id</code>.
     */
    public final TableField<ValuationResultDatasetRecord, Integer> VARIABLE_DATASET_ID = createField(DSL.name("variable_dataset_id"), SQLDataType.INTEGER, this, "");

    private ValuationResultDataset(Name alias, Table<ValuationResultDatasetRecord> aliased) {
        this(alias, aliased, null);
    }

    private ValuationResultDataset(Name alias, Table<ValuationResultDatasetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>data.valuation_result_dataset</code> table reference
     */
    public ValuationResultDataset(String alias) {
        this(DSL.name(alias), VALUATION_RESULT_DATASET);
    }

    /**
     * Create an aliased <code>data.valuation_result_dataset</code> table reference
     */
    public ValuationResultDataset(Name alias) {
        this(alias, VALUATION_RESULT_DATASET);
    }

    /**
     * Create a <code>data.valuation_result_dataset</code> table reference
     */
    public ValuationResultDataset() {
        this(DSL.name("valuation_result_dataset"), null);
    }

    public <O extends Record> ValuationResultDataset(Table<O> child, ForeignKey<O, ValuationResultDatasetRecord> key) {
        super(child, key, VALUATION_RESULT_DATASET);
    }

    @Override
    public Schema getSchema() {
        return Data.DATA;
    }

    @Override
    public Identity<ValuationResultDatasetRecord, Integer> getIdentity() {
        return (Identity<ValuationResultDatasetRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ValuationResultDatasetRecord> getPrimaryKey() {
        return Keys.VALUATION_RESULT_DATASET_PKEY;
    }

    @Override
    public List<UniqueKey<ValuationResultDatasetRecord>> getKeys() {
        return Arrays.<UniqueKey<ValuationResultDatasetRecord>>asList(Keys.VALUATION_RESULT_DATASET_PKEY);
    }

    @Override
    public ValuationResultDataset as(String alias) {
        return new ValuationResultDataset(DSL.name(alias), this);
    }

    @Override
    public ValuationResultDataset as(Name alias) {
        return new ValuationResultDataset(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ValuationResultDataset rename(String name) {
        return new ValuationResultDataset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ValuationResultDataset rename(Name name) {
        return new ValuationResultDataset(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
