/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.grids.tables;


import gov.epa.bencloud.server.database.jooq.grids.Grids;
import gov.epa.bencloud.server.database.jooq.grids.Indexes;
import gov.epa.bencloud.server.database.jooq.grids.Keys;
import gov.epa.bencloud.server.database.jooq.grids.tables.records.UsCountyRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsCounty extends TableImpl<UsCountyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>grids.us_county</code>
     */
    public static final UsCounty US_COUNTY = new UsCounty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsCountyRecord> getRecordType() {
        return UsCountyRecord.class;
    }

    /**
     * The column <code>grids.us_county.gid</code>.
     */
    public final TableField<UsCountyRecord, Integer> GID = createField(DSL.name("gid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>grids.us_county.name</code>.
     */
    public final TableField<UsCountyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(90), this, "");

    /**
     * The column <code>grids.us_county.state_name</code>.
     */
    public final TableField<UsCountyRecord, String> STATE_NAME = createField(DSL.name("state_name"), SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>grids.us_county.state_fips</code>.
     */
    public final TableField<UsCountyRecord, String> STATE_FIPS = createField(DSL.name("state_fips"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>grids.us_county.cnty_fips</code>.
     */
    public final TableField<UsCountyRecord, String> CNTY_FIPS = createField(DSL.name("cnty_fips"), SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>grids.us_county.fips</code>.
     */
    public final TableField<UsCountyRecord, String> FIPS = createField(DSL.name("fips"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>grids.us_county.col</code>.
     */
    public final TableField<UsCountyRecord, Short> COL = createField(DSL.name("col"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>grids.us_county.row</code>.
     */
    public final TableField<UsCountyRecord, Short> ROW = createField(DSL.name("row"), SQLDataType.SMALLINT, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<UsCountyRecord, Object> GEOM = createField(DSL.name("geom"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "");

    private UsCounty(Name alias, Table<UsCountyRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsCounty(Name alias, Table<UsCountyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>grids.us_county</code> table reference
     */
    public UsCounty(String alias) {
        this(DSL.name(alias), US_COUNTY);
    }

    /**
     * Create an aliased <code>grids.us_county</code> table reference
     */
    public UsCounty(Name alias) {
        this(alias, US_COUNTY);
    }

    /**
     * Create a <code>grids.us_county</code> table reference
     */
    public UsCounty() {
        this(DSL.name("us_county"), null);
    }

    public <O extends Record> UsCounty(Table<O> child, ForeignKey<O, UsCountyRecord> key) {
        super(child, key, US_COUNTY);
    }

    @Override
    public Schema getSchema() {
        return Grids.GRIDS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.US_COUNTY_GEOM_IDX);
    }

    @Override
    public Identity<UsCountyRecord, Integer> getIdentity() {
        return (Identity<UsCountyRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UsCountyRecord> getPrimaryKey() {
        return Keys.US_COUNTY_PKEY;
    }

    @Override
    public List<UniqueKey<UsCountyRecord>> getKeys() {
        return Arrays.<UniqueKey<UsCountyRecord>>asList(Keys.US_COUNTY_PKEY);
    }

    @Override
    public UsCounty as(String alias) {
        return new UsCounty(DSL.name(alias), this);
    }

    @Override
    public UsCounty as(Name alias) {
        return new UsCounty(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsCounty rename(String name) {
        return new UsCounty(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsCounty rename(Name name) {
        return new UsCounty(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, String, String, Short, Short, Object> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
