/*
 * This file is generated by jOOQ.
 */
package gov.epa.bencloud.server.database.jooq.grids.tables;


import gov.epa.bencloud.server.database.jooq.grids.Grids;
import gov.epa.bencloud.server.database.jooq.grids.Indexes;
import gov.epa.bencloud.server.database.jooq.grids.Keys;
import gov.epa.bencloud.server.database.jooq.grids.tables.records.UsNationRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsNation extends TableImpl<UsNationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>grids.us_nation</code>
     */
    public static final UsNation US_NATION = new UsNation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsNationRecord> getRecordType() {
        return UsNationRecord.class;
    }

    /**
     * The column <code>grids.us_nation.gid</code>.
     */
    public final TableField<UsNationRecord, Integer> GID = createField(DSL.name("gid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>grids.us_nation.col</code>.
     */
    public final TableField<UsNationRecord, Short> COL = createField(DSL.name("col"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>grids.us_nation.row</code>.
     */
    public final TableField<UsNationRecord, Short> ROW = createField(DSL.name("row"), SQLDataType.SMALLINT, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<UsNationRecord, Object> GEOM = createField(DSL.name("geom"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "");

    private UsNation(Name alias, Table<UsNationRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsNation(Name alias, Table<UsNationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>grids.us_nation</code> table reference
     */
    public UsNation(String alias) {
        this(DSL.name(alias), US_NATION);
    }

    /**
     * Create an aliased <code>grids.us_nation</code> table reference
     */
    public UsNation(Name alias) {
        this(alias, US_NATION);
    }

    /**
     * Create a <code>grids.us_nation</code> table reference
     */
    public UsNation() {
        this(DSL.name("us_nation"), null);
    }

    public <O extends Record> UsNation(Table<O> child, ForeignKey<O, UsNationRecord> key) {
        super(child, key, US_NATION);
    }

    @Override
    public Schema getSchema() {
        return Grids.GRIDS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.US_NATION_GEOM_IDX);
    }

    @Override
    public Identity<UsNationRecord, Integer> getIdentity() {
        return (Identity<UsNationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UsNationRecord> getPrimaryKey() {
        return Keys.US_NATION_PKEY;
    }

    @Override
    public List<UniqueKey<UsNationRecord>> getKeys() {
        return Arrays.<UniqueKey<UsNationRecord>>asList(Keys.US_NATION_PKEY);
    }

    @Override
    public UsNation as(String alias) {
        return new UsNation(DSL.name(alias), this);
    }

    @Override
    public UsNation as(Name alias) {
        return new UsNation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsNation rename(String name) {
        return new UsNation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsNation rename(Name name) {
        return new UsNation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Short, Short, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
