CREATE TABLE stage.population_entry_for_2024
(
  RACEID SMALLINT
, GENDERID SMALLINT
, AGERANGEID SMALLINT
, ETHNICITYID SMALLINT
, CCOLUMN INTEGER
, "ROW" INTEGER
, VVALUE NUMERIC
);

CREATE TABLE stage.population_growth_for_2024
(
  RACEID SMALLINT
, GENDERID SMALLINT
, AGERANGEID SMALLINT
, ETHNICITYID SMALLINT
, CCOLUMN INTEGER
, "ROW" INTEGER
, YYEAR SMALLINT
, VVALUE NUMERIC
);

CREATE TABLE stage.population_crosswalk_for_2024
(
  SOURCECOLUMN INTEGER
, SOURCEROW INTEGER
, TARGETCOLUMN INTEGER
, TARGETROW INTEGER
, PERCENTAGE NUMERIC
);